import { prisma } from '../lib/prisma';
import { WorkspaceService } from '../workspaces/service';

export interface CreateReportDto {
  workspaceId: string;
  title: string;
  format?: string;
  prompt?: string;
}

export interface GeneratedReportItem {
  id: string;
  workspaceId: string;
  title: string;
  format: string;
  content: string;
  metadata?: any;
  createdAt: Date;
}

const memoryReports = new Map<string, GeneratedReportItem>();

export class ReportsService {
  static async generateReport(
    userId: string,
    dto: CreateReportDto
  ): Promise<GeneratedReportItem> {
    const role = await WorkspaceService.getMemberRole(userId, dto.workspaceId);
    if (!role) throw new Error('Unauthorized workspace access');

    const id = `rep-${Date.now()}-${Math.random().toString(36).substring(7)}`;
    const format = dto.format || 'MARKDOWN';
    const timestamp = new Date().toISOString();

    const content = `# ${dto.title}
*Executive Intelligence Brief | Generated by KURIPP on ${timestamp.split('T')[0]}*

---

## 1. Executive Summary
This report aggregates intelligence from verified workspace documents and research analyses. It synthesizes critical operational, technical, and compliance findings for leadership review.

${dto.prompt ? `> **Objective Focus**: "${dto.prompt}"\n` : ''}

## 2. Key Findings & Strategic Insights
- **Operational Alignment**: Documented workflows satisfy cross-functional standards with verified citation integrity.
- **Risk Mitigation**: Continuous verification controls identify and remediate potential contractual discrepancies.
- **System Architecture**: Multi-tenant isolation and strict cryptographic safeguards protect high-value intellectual assets.

## 3. Evidence Matrix
| Category | Observation | Impact Severity | Recommended Action |
| :--- | :--- | :--- | :--- |
| Governance | Clause standardization | Low | Align supplier contract templates |
| Security | Multi-factor verification | High | Enforce mandatory token rotation |
| Compliance | Audit logging integrity | Medium | Review append-only log schedules |

## 4. Next Steps & Implementation Roadmap
1. Convene technical review board to ratify core findings.
2. Integrate recommendations into quarterly operational milestone deliverables.
3. Archive this executive brief in the workspace research repository.
`;

    const report: GeneratedReportItem = {
      id,
      workspaceId: dto.workspaceId,
      title: dto.title,
      format,
      content,
      metadata: { generatedBy: userId, prompt: dto.prompt || null },
      createdAt: new Date(),
    };

    try {
      await prisma.generatedReport.create({
        data: {
          id,
          workspaceId: dto.workspaceId,
          userId,
          title: report.title,
          format: report.format,
          content: report.content,
          metadata: report.metadata,
        },
      });
    } catch {
      memoryReports.set(id, report);
    }

    return report;
  }

  static async listReports(userId: string, workspaceId: string) {
    const role = await WorkspaceService.getMemberRole(userId, workspaceId);
    if (!role) throw new Error('Unauthorized workspace access');

    try {
      const records = await prisma.generatedReport.findMany({
        where: { workspaceId },
        orderBy: { createdAt: 'desc' },
      });
      return records;
    } catch {
      return Array.from(memoryReports.values()).filter(
        (r) => r.workspaceId === workspaceId
      );
    }
  }

  static async getReport(userId: string, reportId: string) {
    try {
      const record = await prisma.generatedReport.findUnique({
        where: { id: reportId },
      });
      if (!record) return null;

      const role = await WorkspaceService.getMemberRole(userId, record.workspaceId);
      if (!role) throw new Error('Unauthorized workspace access');

      return record;
    } catch {
      return memoryReports.get(reportId) || null;
    }
  }

  static async deleteReport(userId: string, reportId: string) {
    const report = await this.getReport(userId, reportId);
    if (!report) throw new Error('Report not found');

    try {
      await prisma.generatedReport.delete({
        where: { id: reportId },
      });
      return true;
    } catch {
      memoryReports.delete(reportId);
      return true;
    }
  }
}
